"""Data models (dataclass) for DB rows.

These mirror the DB schema exactly. They are plain dataclasses —
no ORM magic, no validation beyond type hints.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class Discovery:
    id: int | None
    source: str
    url: str
    title: str | None = None
    description: str | None = None
    relevance_score: float | None = None
    tags: list[str] = field(default_factory=list)
    target: str | None = None
    status: str = "discovered"
    created_at: datetime | None = None
    updated_at: datetime | None = None


@dataclass
class Improvement:
    id: int | None
    target: str
    summary: str
    discovery_id: int | None = None
    detail: str | None = None
    effort: str | None = None       # S / M / L
    priority: str | None = None     # P0-P3
    status: str = "proposed"
    created_at: datetime | None = None


@dataclass
class Approval:
    id: int | None
    improvement_id: int
    approved_by: str
    chat_id: str
    prompt_snapshot: str
    execution_mode: str
    ttl_minutes: int
    expires_at: datetime
    created_at: datetime | None = None


@dataclass
class Run:
    id: int | None
    target: str
    execution_mode: str
    improvement_id: int | None = None
    approval_id: int | None = None
    prompt_hash: str | None = None
    output_summary: str | None = None
    token_count: int | None = None
    duration_secs: float | None = None
    exit_code: int | None = None
    status: str = "pending"
    created_at: datetime | None = None


@dataclass
class Event:
    id: int | None
    event_type: str
    source: str | None = None
    detail: str | None = None
    created_at: datetime | None = None


@dataclass
class Lock:
    target: str
    holder: str
    ttl_minutes: int = 60
    acquired_at: datetime | None = None


@dataclass
class Session:
    """A persistent conversation session with an AI backend.

    Each session is tied to a chat_id, a working directory, and a backend.
    session_id stores the Claude Code SDK session ID for context continuation.

    Status flow: active → paused (on crash) | closed (on /close)
    """

    id: int | None
    name: str
    chat_id: str
    working_dir: str
    backend: str = "claude"          # claude | codex
    model: str | None = None
    session_id: str | None = None    # Claude Code SDK session_id for context continuation
    status: str = "active"
    created_at: datetime | None = None
    updated_at: datetime | None = None


@dataclass
class SessionMessage:
    """A message exchanged within a Session."""

    id: int | None
    session_id: int
    role: str                        # user | assistant | system
    content: str
    token_count: int = 0
    telegram_message_id: int | None = None
    created_at: datetime | None = None


@dataclass
class Task:
    """User message converted into a tracked task.

    kind: 'unknown' | 'note' | 'question' | 'action'

    Status flow:
      Action:   received → triaging → planned → awaiting_user_decision
                         → approved → executing → done / failed / dead_letter
      Question: received → triaging → answered → closed
      Note:     received → triaging → noted → closed
    Terminal states: done, failed, dead_letter, closed, cancelled
    """

    id: int | None
    raw_message: str
    chat_id: str
    user_id: str
    source_message_id: int | None = None  # Telegram message_id for thread linkage

    # Classification
    kind: str = "unknown"          # unknown / note / question / action
    summary: str | None = None     # one-line summary generated by triage
    plan: str | None = None        # action: Claude-generated execution plan
    answer: str | None = None      # question: Claude's answer
    target: str | None = None      # target project
    priority: str | None = None    # P0-P3
    effort: str | None = None      # S / M / L
    decision_needed: bool = False  # True when awaiting_user_decision

    # Linked IDs
    improvement_id: int | None = None
    approval_id: int | None = None
    run_id: int | None = None

    # Failure governance
    triage_retries: int = 0
    execute_retries: int = 0
    last_error: str | None = None
    next_retry_at: datetime | None = None

    # Status + timestamps
    status: str = "received"
    created_at: datetime | None = None
    updated_at: datetime | None = None
